### ISSUE TITLE
The environment variable IPYTHON_DIR is deprecated.

### ISSUE THREAD

**Issue by jedie** [kaazoo/DrQueueIPython#20]
```
/home/jens/DrQueue_env/local/lib/python2.7/site-packages/IPython/utils/path.py:282: UserWarning: The environment variable IPYTHON_DIR is deprecated. Please use IPYTHONDIR instead.
  warnings.warn('The environment variable IPYTHON_DIR is deprecated. '
```

Just change all **IPYTHON_DIR** to **IPYTHONDIR** in the sources?!?

EDIT: There only a few usage: https://github.com/kaazoo/DrQueueIPython/search?utf8=%E2%9C%93&q=%22IPYTHON_DIR%22

**Comment by kaazoo** [comment]
Fixed by a01aa2a132ab484c803721d8d4329dab07b564c3 .
