### ISSUE TITLE
dqeueue not windows compatible...

### ISSUE THREAD

**Issue by jedie** [kaazoo/DrQueueIPython#23]
e.g.: usage of "ps" here: https://github.com/kaazoo/DrQueueIPython/blob/3b08a0a9ce0231a70c5f93f0017089fb99792169/bin/drqueue#L958-L969

**Comment by kaazoo** [comment]
Do you know if a portable way to do the same in Python?

**Comment by jedie** [comment]
maybe: https://pypi.python.org/pypi/psutil

**Comment by kaazoo** [comment]
Thanks for the hint. This issue should be fixed by 796a65c .

**Comment by jedie** [comment]
Great!

Think psutil can be used in other parts, too. e.g.: display status of slaves etc.
