### ISSUE TITLE
drqueue vs. drqueue_master.py and drqueue_slave.py

### ISSUE THREAD

**Issue by jedie** [kaazoo/DrQueueIPython#28]
I just found:
- https://github.com/kaazoo/DrQueueIPython/blob/master/bin/drqueue_master.py
- https://github.com/kaazoo/DrQueueIPython/blob/master/bin/drqueue_slave.py

But it seems that all code is in:
- https://github.com/kaazoo/DrQueueIPython/blob/master/bin/drqueue

isn't it?!?

Are drqueue_master.py and drqueue_slave.py obsolete code files?!?

**Comment by kaazoo** [comment]
Yes, that seems to be true. The code was merged into the 'drqueue' script.
Fixed by 097cbbf

**Comment by jedie** [comment]
But i would prefere to split bin/drqueue and just store the CLI needed parts there and outsource the real code.
