### ISSUE TITLE
TODO: Use a registration solution for *.sg.py files...

### ISSUE THREAD

**Issue by jedie** [kaazoo/DrQueueIPython#29]
for this: https://github.com/kaazoo/DrQueueIPython/blob/e9daf8f60045e5503af9d44ee6b5ce75ea1e5848/DrQueue/__init__.py#L24-L80

**Comment by kaazoo** [comment]
On startup of the 'drqueue' script, the directory 'etc' could be scanned for '*_sg.py' files. If you delete '_sg.py' from the filename you would get the name of the renderer.

**Comment by kaazoo** [comment]
Renderer support is covered by 4491f13ee7aaa371824b096d72ac167cba8db79a and e16d888c3034f02f98c246c88ab99cb1a2ca2330.

The list of supported operating systems is not used at the moment. I'll leave it like this for now.

**Comment by jedie** [comment]
:+1:
