### ISSUE TITLE
TODO: remove dist_egg.get_resource_filename(__name__, "EGG-INFO/scripts/...")

### ISSUE THREAD

**Issue by jedie** [kaazoo/DrQueueIPython#30]
I think the `dist_egg.get_resource_filename(__name__, "EGG-INFO/scripts/get_slave_information.py")` stuff a little bit strange!

see: https://github.com/kaazoo/DrQueueIPython/search?utf8=%E2%9C%93&q=EGG-INFO%2Fscripts%2Fget_slave_information.py&type=Code

I DrQueue is installed, then `get_slave_information.py` should be in local PATH.

**Comment by kaazoo** [comment]
`ipengine` needs a full path to a Python file to be run as startup script, not a name of a executable.
I used `distutils.spawn.find_executable()` for this. See 0f082baf336c36b472728882084f3bc3f53ba31b

**Comment by jedie** [comment]
Yes, looks like a better solution.

But what's about to add "get_slave_information.py" as a sub cli command in bin/drqueue and use a normal import for the functionality?

**Comment by kaazoo** [comment]
Yes, that would be possible as well.
